spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/vetrostudio
        username: root
        password: 
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
            